import = [
  "~/.config/alacritty/themes/themes/citylights.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
startup_mode = "FullScreen"
padding.x = 0
padding.y = 1

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 14
